#ifndef __GRAPHICS_H__
#define __GRAPHICS_H__

#define GRAPHICS_OFFSET_X 8
#define GRAPHICS_OFFSET_Y 4
#define GRAPHICS_SPRITE_WIDTH 5
#define GRAPHICS_SPRITE_HEIGHT 3
#define GRAPHICS_HEALTH_X 77
#define GRAPHICS_HEALTH_Y 10
#define GRAPHICS_HEALTH_OFFSET_X 6
#define GRAPHICS_HEALTH_OFFSET_Y 2
#define GRAPHICS_SPINNING_ANIMATION_X 99
#define GRAPHICS_SPINNING_ANIMATION_Y 36

typedef enum graphics_sprites_e
{
	GRAPHICS_SPRITES_UNDESTROYABLE = 0,
	GRAPHICS_SPRITES_DESTROYABLE = 1,
	GRAPHICS_SPRITES_DESTROYED = 2,
	GRAPHICS_SPRITES_PLAYER = 3,
	GRAPHICS_SPRITES_ENEMY = 4,
	GRAPHICS_SPRITES_BOMB = 5,
	GRAPHICS_SPRITES_BOMB_UP = 6,
	GRAPHICS_SPRITES_FIRE = 7,
	GRAPHICS_SPRITES_HEART = 8,
	GRAPHICS_SPRITES_SNEAKER = 9,
	GRAPHICS_SPRITES_UP = 10,
	GRAPHICS_SPRITES_SHIELD = 11,
	GRAPHICS_SPRITES_EXPLOSION = 12,
	GRAPHICS_SPRITES_PLAYER_STANDING = 14
} graphics_sprites_t;

void graphics_render_sprite(int pos_x, int pos_y, graphics_sprites_t field, char transparency);
void graphics_main(void);

#endif /* __GRAPHICS_H__ */
